blog_Yii_2/blog/protected/modules/blog/models/Message.php
<?php
class Message extends CActiveRecord
{
	private $oldId;
	private $oldLanguage;
	
	/**
     * Возвращает статическую модель указанного класса AR.
     *return CActiveRecord статический класс модели
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
     *return Строка связана имя таблицы базы данных
	 */
	public function tableName()
	{
		return '{{message}}';
	}

	/**
     * Правила проверки return массив для атрибутов модели.
	 */
	public function rules()
	{
		return array(
			array('language', 'required'),
                        array('language', 'default', 'setOnEmpty' => true, 'value' => 'ru'),
			array('id, language, translation', 'safe', 'on' => 'search'),
			array('id', 'numerical', 'min' => 1),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
        // ПРИМЕЧАНИЕ: Вы, возможно, потребуется настроить имя отношения и связанные с
// Имя класса для отношений, автоматически сгенерированных ниже.
		return array(
			'lang' => array(self::BELONGS_TO, 'Language', 'language'),
		);
	}

	/**
     *return Массив индивидуальные этикетки атрибутов (имя => label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Message::getTranslation(27),
			'language' => Message::getTranslation(35),
			'translation' => Message::getTranslation(46),
		);
	}
	
	public static function getTranslation($id)
	{
		$translation = '';
		$message = Message::model()->find(array('condition' => 'id = :id AND language = :lang', 'params' => array(':id' => $id, ':lang' => Yii::app()->getLanguage())));
		if(is_null($message))
		{
			$message = Message::model()->findByPk(array('id' => $id, 'language' => Parameter::getValue(29)));
			if(is_null($message))
				$translation = "Нет доступных сообщений";
			else
				$translation = $message->translation;		
		}
		else
		{
			$translation = $message->translation;
		}
		return $translation;
	}

	/**
    / **
     * Получает список категорий на основе текущих условий поиска / фильтров.
     *return CActiveDataProvider поставщика данных, который может вернуть необходимые сообщения.
	 */
	public function search()
	{
		$criteria=new CDbCriteria;
		$criteria->compare('id',$this->id);
		$criteria->compare('language',$this->language);
		$criteria->compare('translation',$this->translation, true);

		return new CActiveDataProvider('Message', array(
			'criteria'=>$criteria,
			'sort'=>array(
				'defaultOrder'=>'language, id ASC',
			),
			'pagination'=>array(
				'pageSize'=>Parameter::getValue(16),
			),
		));
	}
	
	public function afterFind()
	{
		$this->oldId = $this->id;
		$this->oldLanguage = $this->language;
	}
}
	

blog_Yii_2/blog/protected/modules/blog/controllers/MessageController.php
<?php

class MessageController extends BlogController
{
	public $layout = '//layouts/blog';
	/**
	 * @var CActiveRecord текущий загруженный экземпляр модели данных.
	 */
	private $_model;
	/**
	 * @return фильтры действий массив
	 */
	public function filters()
	{
		$filters = array(
			'accessControl', //осуществляется контроль доступа к CRUD операциям
		);
		
		return array_merge($filters, parent::filters());
	}

	/**
	 * Определяет правила управления доступом.
     * Этот метод используется фильтром '' AccessControl.
     * return Правила контроля доступа к массиву
	 */
	public function accessRules()
	{
		return array(
			array('allow', // позволяют пользователи с правами администратора для доступа к всем действиям
				'roles'=>array('admin'),
			),
			array('deny',  // все пользователи
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 */
	public function actionCreate()
	{
		$model=new Message;
		if(isset($_POST['Message']))
		{
			$model->attributes=$_POST['Message'];
			if($model->save())
			{
				Yii::app()->user->setFlash('flash',Message::getTranslation(89));
				$this->redirect(array('admin', 'lang' => $_POST['lang']));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Обновления конкретной модели.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();
		
		if(isset($_POST['Message']))
		{
			$model->attributes=$_POST['Message'];

			if($model->save())
			{
				Yii::app()->user->setFlash('flash',Message::getTranslation(90));
				$this->redirect(array('admin', 'lang' => $_POST['lang']));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 *Удаляет конкретную модель.
	 */
	public function actionDelete()
	{
		//  только позволит исключить через POST запрос
		$this->loadModel()->delete();

		// если AJAX запрос (вызвано удаление с помощью  администратора сетки), мы не должны перенаправить браузер
		if(!isset($_GET['ajax']))
		{
			Yii::app()->user->setFlash('flash',Message::getTranslation(91));
			$this->redirect(array('admin', 'lang' => $_GET['lang']));
		}
	}
	
	
	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Message('search');
		$model->unsetAttributes();
		if(isset($_GET['Message']))
			$model->attributes=$_GET['Message'];
		$this->render('admin',array(
			'model'=>$model,
		));
	}


	/**
	 * Возвращает модель данных на основе первичного ключа, указанному в переменной GET.
     * Если модель данных не найдена,в HTTP будет  исключение.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['message']))
			{
				$this->_model=Message::model()->findByPk(array('id' => $_GET['message'], 'language' => $_GET['language']));
			}
			if($this->_model===null)
				throw new CHttpException(404,Message::getTranslation(94));
		}
		return $this->_model;
	}
}

blog_Yii_2/blog/protected/modules/blog/views/message/_form.php
<?php
	Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl . '/css/form.css');
?>
<div class="form">
<?php $form=$this->beginWidget('CActiveForm'); ?>

	<p class="note"><?= Message::getTranslation(8) ?></p>

	<?php echo CHtml::errorSummary($model); ?>

	<!--<div class="row">
		<?php //echo $form->labelEx($model,'id'); ?>
		<?php //echo $form->textField($model,'id',array('style'=>'width:100%')); ?>
		<?php //echo $form->error($model,'id'); ?>
	</div>-->
	
	<!--<div class="row">
		<?php //echo $form->labelEx($model,'language'); ?>
		<?php //echo $form->dropDownList($model,'language',Language::getLanguagesOptions()); ?>
		<?php //echo $form->error($model,'language'); ?>
	</div>-->
	
	<div class="row">
		<?php echo $form->labelEx($model,'translation'); ?>
		<?php echo $form->textField($model,'translation',array('style'=>'width:100%')); ?>
		<?php echo $form->error($model,'translation'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? Message::getTranslation(50) : Message::getTranslation(70), array('class' => 'bigbutton')); ?>
	</div>
	<?= CHtml::hiddenField('lang', Yii::app()->getLanguage()) ?>

<?php $this->endWidget(); ?>

</div><!-- form -->

blog_Yii_2/blog/protected/modules/blog/views/message/admin.php
<?php
$this->pageTitle = Message::getTranslation(68);
$this->breadcrumbs=array(
	Message::getTranslation(68),
);
$style ='	@media 
	all and (max-width: 950px),
	(min-device-width: 768px) and (max-device-width: 1024px)  {
		td:nth-of-type(1):before { content: "' . Message::getTranslation(27) . '"; }
		td:nth-of-type(2):before { content: "' . Message::getTranslation(35) . '"; }
		td:nth-of-type(3):before { content: "' . Message::getTranslation(46) . '"; }
		td:nth-of-type(4):before { content: "' . Message::getTranslation(139) . '"; }
	}';
Yii::app()->getClientScript()->registerCss('style', $style);
?>
<?php if(Yii::app()->user->hasFlash('flash')): ?>
<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('flash'); ?>
</div>
<?php endif; ?>
<h1><?= Message::getTranslation(68) ?></h1>
<div style="text-align:center;margin-bottom:20px;">
<?php echo CHtml::link(Message::getTranslation(50),array('message/create', 'lang' => Yii::app()->getLanguage()), array('class' => 'btncreate')); ?>
</div>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'pager' => array('cssFile' => Yii::app()->baseUrl . '/css/gridview.css'),
	'cssFile' => Yii::app()->baseUrl . '/css/gridview.css',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'htmlOptions' => array('class' => 'grid-view rounded'),
	'ajaxUpdate'=>false,
	'columns'=>array(
		array(
			'name'=>'id',
			'type'=>'raw',
			'value'=>'$data->id',
    		'htmlOptions'=>array('style'=>'width:40px'),
		),
		/*array(
			'name'=>'language',
			'value'=>'$data->lang->name',
			'filter'=>Language::getLanguagesOptions(),
    		'htmlOptions'=>array('style'=>'width:100px'),			
		),*/
		array(
			'name'=>'translation',
			'type'=>'raw',
			'value'=>'$data->translation',
		),
        array(
            'header' => Message::getTranslation(49),
            'class' => 'CButtonColumn',
            'template' => '{update}&nbsp;&nbsp;&nbsp;{delete}',
            'viewButtonImageUrl' => Yii::app()->baseUrl . '/images/gridview/' . 'gr-view.png',
            'updateButtonImageUrl' => Yii::app()->baseUrl . '/images/gridview/' . 'gr-update.png',
            'deleteButtonImageUrl' => Yii::app()->baseUrl . '/images/gridview/' . 'gr-delete.png',
	        'buttons'=>array
			(
		       'update' => array
		        (
		        	'url'=>'Yii::app()->createUrl("/blog/message/update", array("message"=>$data->id, "language"=>$data->language, "lang" => Yii::app()->getLanguage()))'
		        ),
		       'delete' => array
		        (
		        	'url'=>'Yii::app()->createUrl("/blog/message/delete", array("message"=>$data->id, "language"=>$data->language, "lang" => Yii::app()->getLanguage()))'
		        ),
			),
         ),
	),
)); ?>

blog_Yii_2/blog/protected/modules/blog/views/message/create.php
<?php
$this->pageTitle = Message::getTranslation(62);
$this->breadcrumbs=array(
	Message::getTranslation(62),
);
?>
<h1><?= Message::getTranslation(62) ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

blog_Yii_2/blog/protected/modules/blog/views/message/update.php
<?php
$this->pageTitle = Message::getTranslation(56);
$this->breadcrumbs=array(
	Message::getTranslation(56),
);
?>

<h1><?= Message::getTranslation(56) ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>