blog_Yii_2/blog/protected/modules/blog/models/Comment.php
<?php

class Comment extends CActiveRecord
{
	public $postCount;
	public $verifyCode;
	public $maxId;
	const STATUS_PENDING=1;
	const STATUS_APPROVED=2;

	/**
	 * R **
     * Возвращает статическую модель указанного класса AR.
     *return CActiveRecord статический класс модели
     * /
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * / **
     *return Строка связана имя таблицы базы данных
     * /
	 */
	public function tableName()
	{
		return '{{comment}}';
	}

	/**
	 ** Правила проверкиreturn массив для атрибутов модели.
	 */
	public function rules()
	{
		$p = new CHtmlPurifier();
		$p->options = array('HTML.Nofollow'=> true);	
		return array(
			array('content, status', 'required'),
			array('author, email', 'required', 'on' => 'guestcomment, updateguest'),
			array('content', 'length', 'max'=>1000),
			array('author, email, url', 'length', 'max'=>128),
			array('email','email'),
			array('url','url'),
			array('comment_id','numerical'),
			array('id, content, post_id, status, user_id, author', 'safe', 'on'=>'search'),
			array('url, content, author','filter','filter'=>array($p,'purify')),
			array('verifyCode', 'captcha', 'allowEmpty'=>!CCaptcha::checkRequirements(), 'on' => 'guestcomment'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array(
			//'post' => array(self::BELONGS_TO, 'Post', array('post_id', 'category_id', 'language')),
                        'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}
	
	/**
	 *return массив настроены этикетки атрибутов (имя => label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Message::getTranslation(27),
			'content' => Message::getTranslation(13),
			'status' => Message::getTranslation(30),
			'create_time' => Message::getTranslation(31),
			'author' => Message::getTranslation(33),
			'email' => Message::getTranslation(11),
			'url' => Message::getTranslation(12),
			'post_id' => Message::getTranslation(38),
			'comment_id' => Message::getTranslation(39),
			'user_id' => Message::getTranslation(112),
		);
	}

	public function getApprovedComments()
	{
		return Comment::model()->findAll("comment_id = ? AND post_id = ? AND category_id = ? AND language = ? AND status = ?", array($this->id, $this->post_id, $this->category_id, $this->language, Comment::STATUS_APPROVED));
	}

	public function getAllComments()
	{
		return Comment::model()->findAll("comment_id = ? AND post_id = ? AND category_id = ? AND language = ?", array($this->id, $this->post_id, $this->category_id, $this->language));
	}
	
	/**
	 * Утверждает комментарий.
	 */
	public function approve()
	{
		$this->status=Comment::STATUS_APPROVED;
		$this->update(array('status'));
	}

	/**
	 * param Сообщение пост, что этот комментарий относится. Если NULL, метод
     * Будет запрашивать должность.
     *return Строка Постоянная ссылка URL для этого комментария
     * /
	 */
	public function getUrl($post=null)
	{
		if($post===null)
			$post=$this->post;
		return $post->url.'#c'.$this->id;
	}

	/**
	 * *return Строка дисплея гиперссылка на автора текущего комментария
     * /
	 */
	public function getAuthorLink()
	{
		if(is_null($this->user_id)){
			if(!empty($this->url) && Parameter::getValue(17))
				return '<span class="jslink" style="cursor:pointer" title="' . CHtml::encode($this->url) . '">' . CHtml::encode($this->author) . '</span>';
			else
				return CHtml::encode($this->author);
		}
		else {
			if(Yii::app()->user->isGuest)
				return $this->user->username;
			else
				return CHtml::link(CHtml::encode($this->user->username),array('/blog/user/view', 'user' => $this->user_id, 'lang' => Yii::app()->getLanguage()));
		}
	}

	/**
	 * *return Целое число комментариев, ожидающих одобрения
	 */
	public function getPendingCommentCount()
	{
		return $this->count('status='.self::STATUS_PENDING);
	}

	/**
	 * / **
     *param Число максимальное количество комментариев, которые должны быть возвращены
     *return Массив наиболее недавно добавленные комментарии
     * /
	 */
	public function findRecentComments($limit=10)
	{
		$categories = substr(Category::getSubcategoriesIdsR(Category::model()->findAll(array('condition' => 'language =:language AND category_id IS NULL','order' => 'LOWER(name) ASC', 'params' => array(':language' => Yii::app()->getLanguage())))),1);
		return $this->with('post')->findAll(array(
			'condition'=>'t.status='.self::STATUS_APPROVED . ' AND t.language=\'' . Yii::app()->getLanguage() . '\' AND post.status=' . Post::STATUS_PUBLISHED . ' AND t.category_id IN(' . $categories . ')' ,
			'order'=>'t.create_time DESC',
			'limit'=>$limit,
		));
	}

	/**
     * Это вызывается перед запись сохранена.
     *return Булево должны ли сохранены запись.
	 */
	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->isNewRecord)
			{
				$comment = Comment::find(array('select' => 'MAX(id) as maxId', 'condition' => 'post_id = ? AND category_id = ? AND language = ?', 'params' => array($this->post_id, $this->category_id, $this->language)));
				$this->id = $comment->maxId + 1;
				$this->create_time=time();
			}
			return true;
		}
		else
			return false;
	}

	/**
	 * / **
     * Получает список сообщений, основываясь на текущих условиях поиск / фильтр.
     *return CActiveDataProvider поставщика данных, который может вернуть необходимые сообщения.
     * /
	 */
	public function search()
	{
		$criteria=new CDbCriteria;
		$criteria->alias='c';
		$criteria->with = array('post'=>array('alias'=>'p'), 'user'=>array('alias'=>'u'));
		$criteria->compare('p.title', $this->post_id,true);
		$criteria->compare('c.id',$this->id);
		$criteria->compare('c.content',$this->content,true);
		$criteria->compare('c.status',$this->status);
		$criteria->compare('u.username',$this->user_id,true);
		$criteria->compare('c.author',$this->author,true);
		if(Yii::app()->user->checkAccess('reader') || Yii::app()->user->checkAccess('author') || 
		Yii::app()->user->checkAccess('editor') || Yii::app()->user->checkAccess('publisher'))
			$criteria->compare('c.user_id', Yii::app()->user->id);
		
		return new CActiveDataProvider('Comment', array(
			'criteria'=>$criteria,
			'sort'=>array(
				'defaultOrder'=>'c.status, c.create_time DESC',
			),
			'pagination'=>array(
				'pageSize'=>Parameter::getValue(9),
			),
		));
	}
	
	protected function beforeDelete()
	{
		if(count($this->getAllComments()) > 0)
		{
			return false;
		}
		
		return true;
	}
}

blog_Yii_2/blog/protected/modules/blog/models/Post.php
<?php
// название модели, это название таблицы базы данных, но в базе данных пишется ещё tbl-префикс
class Post extends CActiveRecord
{
	const STATUS_DRAFT=1;
	const STATUS_PUBLISHED=2;
	const STATUS_ARCHIVED=3;

	private $_oldTags;
	public $oldId;
	public $oldCategory;
	public $oldLanguage;
	public $postyear; // Используется в виджете архивов
	public $postmonth; // Используется в виджете архивов
	public $postspermonth; // Используется в виджете архивов
	public $maxId;
	
	/**
	 * Возвращает статическую модель указанного класса AR.
     *return CActiveRecord статический класс модели
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 *return строка связана имя таблицы базы данных
	 */
	public function tableName()
	{
		return '{{post}}';
        // это значит, что берётся название модели Post и из config
        // возвращаем название таблицы, от которой берётся эта модель.
	}

	/**
     * Правила проверки return массив для атрибутов модели.
	 */
        /**
         * Тут прописаны правила проверки для каждого поля модели
         * все поля модели можно увидеть в верху в комментарии
         * @return type
         */
	public function rules()
	{
		$p = new CHtmlPurifier();
		//$p->options = array('HTML.AllowedCommentsRegexp'=> '/.*/');
		$p->options = array('HTML.AllowedComments'=> array('pagebreak'));	
		return array(
			array('title, content, status, category_id', 'required'),
            // обязательные поля *
			array('id', 'numerical', 'min' => 1, 'max' => 9999999999),
            // id должен быть числом..
			array('status', 'in', 'range'=>array(1,2,3)),
            // status-число в интервале ...
			array('title', 'length', 'max'=>128),
			array('tags', 'match', 'pattern'=>'/^[\p{L}\s,0-9]+$/u', 'message'=>Message::getTranslation(101)),
			array('tags', 'normalizeTags'),// когда мы записываем тэги, они должны удовлетворять легулярному выражению.
            //регулярка говорит:Могут быть пробелы, символы, цифры от 0-9,)
			array('meta_keywords, meta_description', 'default', 'setOnEmpty' => true, 'value' => null),
                        array('language','default', 'setOnEmpty' => true, 'value' => 'ru'),
			array('id, title, status, category_id, language, user_id', 'safe', 'on'=>'search'),
            //safe-когда мы даём поиск то поля id, title, status, category_id, language, user_id' могут быть любыми/можем
            //что то не ввести и сделать поиск.
			array('title, tags, meta_keywords, meta_description','filter','filter'=>array(new CHtmlPurifier(),'purify')),
			array('content','filter','filter'=>array($p,'purify')),
            //CHtmlPurifier()-защита от введения какого либо кода
            // мы проверяем title, tags, meta_keywords, meta_description','filter'
	        //array('id', 'checkPost', 'on' => 'insert, update'),
		);
	}
// Правилa по которым работают формы. Любое поле при заполнении таблицы должно быть определённых правил.(только числа, толко символы...)

	/**
	 * @return Массив  правил.
	 */
        /**
         * Тут прописаны связи модели с другими моделями,
         * по сути это типа связи между таблицами
         * BELONGS_TO USER - это значит что эта модель то есть пост относится к одному пользователю
         * HAS_MANY COMMENT - это значит что эта модель может иметь много комментариев
         * @return type
         */
	public function relations()
	{
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'comments' => array(self::HAS_MANY, 'Comment', array('post_id', 'category_id', 'language'), 'condition'=>'comments.status='.Comment::STATUS_APPROVED . ' AND comments.comment_id IS NULL', 'order'=>'comments.create_time DESC'),
			'category' => array(self::BELONGS_TO, 'Category', array('category_id', 'language')),
		);
	}

	/**
     *return Массив индивидуальные атрибутов (имя => label)
	 */
        /**
         * ФОрма добавления поста или его редактирования имеет поля
         * ТУт указаны названия полей, то есть лейблы к ним
         * Message::getTranslation - говорит о том что все названия берутся их таблицы tpl_messages по ID
         * 
         * @return type
         */
	public function attributeLabels()
	{
		return array(
			'id' => Message::getTranslation(27),
			'title' => Message::getTranslation(28),
			'content' => Message::getTranslation(29),
			'tags' => Message::getTranslation(4),
			'status' => Message::getTranslation(30),
			'create_time' => Message::getTranslation(31),
			'update_time' => Message::getTranslation(32),
			'user_id' => Message::getTranslation(33),
			'category_id' => Message::getTranslation(34),
			'language' => Message::getTranslation(35),
			'meta_keywords' => Message::getTranslation(36),
			'meta_description' => Message::getTranslation(37),
			'commentCount' => '#' . substr(Message::getTranslation(17),0,3),
		);
	}

        /**
         * Получаем количество комментариев на определенный пост
         * @return type
         */
	public function getCommentCount()
	{
		return Comment::model()->count('post_id = ? AND language = ? AND status = ?', array($this->id, $this->language, Comment::STATUS_APPROVED));
	}
	
	/**
	 * return строка URL, который показывает деталь сообщению
	 */
        /**
         * Получаем URL к этому посту
         * URL относительный
         */
	public function getUrl()
	{
		$url = array();
		$url['post'] = $this->id;
		$url['category'] = $this->category_id;
		$url['title'] = $this->sanitizeString($this->title);
		$url['lang'] = $this->language;
		return Yii::app()->createUrl('blog/post/view', $url);
	}

        /**
         * Получаем абсолютный URL к посту
         * @return type
         */
	public function getAbsoluteUrl()
	{
		$url = array();
		$url['post'] = $this->id;
		$url['category'] = $this->category_id;
		$url['title'] = $this->sanitizeString($this->title);
		$url['lang'] = $this->language;
		return Yii::app()->createAbsoluteUrl('blog/post/view', $url);
	}
	
        /**
         * По идее это замена на спец символы, 
         * @param type $string
         * @return type
         */
	public function sanitizeString($string)
	{
	
	    $string = trim($string);
	
	    $string = str_replace(
	        array('á', 'à', 'ä', 'â', 'ª', 'Á', 'À', 'Â', 'Ä'),
	        array('a', 'a', 'a', 'a', 'a', 'A', 'A', 'A', 'A'),
	        $string
	    );
	
	    $string = str_replace(
	        array('é', 'è', 'ë', 'ê', 'É', 'È', 'Ê', 'Ë'),
	        array('e', 'e', 'e', 'e', 'E', 'E', 'E', 'E'),
	        $string
	    );
	
	    $string = str_replace(
	        array('í', 'ì', 'ï', 'î', 'Í', 'Ì', 'Ï', 'Î'),
	        array('i', 'i', 'i', 'i', 'I', 'I', 'I', 'I'),
	        $string
	    );
	
	    $string = str_replace(
	        array('ó', 'ò', 'ö', 'ô', 'Ó', 'Ò', 'Ö', 'Ô'),
	        array('o', 'o', 'o', 'o', 'O', 'O', 'O', 'O'),
	        $string
	    );
	
	    $string = str_replace(
	        array('ú', 'ù', 'ü', 'û', 'Ú', 'Ù', 'Û', 'Ü'),
	        array('u', 'u', 'u', 'u', 'U', 'U', 'U', 'U'),
	        $string
	    );
	
	    $string = str_replace(
	        array('ñ', 'Ñ', 'ç', 'Ç'),
	        array('n', 'N', 'c', 'C',),
	        $string
	    );
	
	    $string = str_replace(
	        array("\\", "¨", "º", "-", "~",
	             "#", "@", "|", "!", "\"",
	             "·", "$", "%", "&", "/",
	             "(", ")", "?", "'", "¡",
	             "¿", "[", "^", "`", "]",
	             "+", "}", "{", "¨", "´",
	             ">", "< ", ";", ",", ":",
	             "."),
	        '',
	        $string
	    );
		
		$string = strtolower($string);
		
		$string = str_replace(' ', '-', $string);
	
	    return $string;
	}

	/**
	 *return массив список ссылок, которые указывают на список почты фильтруется каждого тега этого поста
	 */
        /**
         * Получение ссылок на теги
         * @return type
         */
	public function getTagLinks()
	{
		$links=array();
		foreach(Tag::string2array($this->tags) as $tag)
			$links[]=CHtml::link(CHtml::encode($tag), array('post/index', 'tag'=>preg_replace(array('|\s+|','/\W-/'), array('-','-'), $tag), 'lang' => $this->language), array('rel' => Parameter::getValue(32) ? 'nofollow' : null));
		return $links;
	}

	/**
	 * Нормализует введенные пользователем теги.
	 */
        /**
         * Формирования тегов к посту (они получены из связей между таблицами - relations) в строку через запятую
         * @param type $attribute
         * @param type $params
         */
	public function normalizeTags($attribute,$params)
	{
		$this->tags=Tag::array2string(array_unique(Tag::string2array($this->tags)));
	}

    /**
     *Добавляет новый комментарий к этому сообщению.
     * Этот метод будет установлено состояние и post_id комментария соответственно.
     *param Комментарий комментарий будет добавлен
     *return Булево ли комментарий успешно сохранен
     */
        
        /**
         * Добавлени комментариев, используются константы статусов, которые прописаны в модели Comment
         * @param type $comment
         * @return type
         */
	public function addComment($comment)
	{
		if(Yii::app()->user->checkAccess('admin'))
		{
			$comment->status=Comment::STATUS_APPROVED;
		}
		else
		{
			if(Parameter::getValue(6))
				$comment->status=Comment::STATUS_PENDING;
			else
				$comment->status=Comment::STATUS_APPROVED;
		}
		
		$comment->post_id=$this->id;
		$comment->category_id=$this->category_id;
		$comment->language=$this->language;
		$comment->user_id = Yii::app()->user->id;
		
                return $comment->save();
	}

	/**
	 * This is invoked when a record is populated with data from a find() call.
	 */
        /**
         * Вызывается после поиска модели, сохраняет ее старые данные, например применяется при изменении
         */
	protected function afterFind()
	{
		parent::afterFind();
		$this->_oldTags=$this->tags;
		$this->oldId = $this->id;
		$this->oldCategory = $this->category_id;
		$this->oldLanguage = $this->language;
	}

	/**

	 */
        /**
         * Вызывается перед сохранением поста

blog_Yii_2/blog/protected/modules/blog/views/post/_comments.php
<?php
	$commentReply ="	
			$('.replycomment').click(function(){
				$('#Comment_comment_id').attr('value', $(this).parent().parent().parent().parent().attr('id').substring(1));
			});";
	$jslink = "$('.jslink').click(function(){
				window.open($(this).attr('title'), '_blank');
			});";
	$cs = Yii::app()->getClientScript();
	$cs->registerScript('commentReply', $commentReply);
	$cs->registerScript('jslink', $jslink);

	$this->widget('zii.widgets.CListView', array(
		'dataProvider'=>$comments,
		'itemView'=>'_commentview',
		'viewData' => array('post' => $post), 
		'template'=>"{items}\n{pager}",
	));
?>

<?php 
function printComments($comments, $post)
{
	foreach($comments as $key => $comment): 
?>
	<article style="word-wrap: break-word;border:1px dotted black;<?= is_null($comment->comment_id) ? '' : "margin-left:20px" ?>" class="comment" id="c<?php echo $comment->id; ?>">
		<div style="display:table;width:100%">
			<div style="display:table-cell;width:6%;vertical-align: top;">
				<?php
					echo CHtml::image(Yii::app()->baseUrl . '/' . User::IMAGE_DIRECTORY . (is_null($comment->user_id) ? User::DEFAULT_IMAGE : $comment->user->getImageFile()), '', array('class' => 'avatar'));
				?>				
			</div>
			<div style="display:table-cell;padding-left:10px">
				<header style="padding-bottom:5px;border-bottom: 1px solid silver;">
					<b><?php echo $comment->authorLink; ?>&nbsp;&nbsp;&nbsp;
					<?php echo date('j ',$comment->create_time) . Message::getTranslation(114 + date('n',$comment->create_time)) . date(', Y h:i a',$comment->create_time); ?>&nbsp;&nbsp;&nbsp;</b>
					<?php echo CHtml::link(Message::getTranslation(100), '#comment-form', array('class' => 'replycomment', 'rel' => 'nofollow')); ?>&nbsp;&nbsp;&nbsp;
					<?php echo CHtml::link(Message::getTranslation(197), $comment->getUrl($post), array('title'=>Message::getTranslation(196), 'rel' => 'nofollow')); ?>
				</header>
				<div style="padding-top: 10px;padding-bottom: 10px;">
						<?php echo nl2br($comment->content); ?>
				</div>
			</div>
		</div>
		<?php 
			printComments($comment->getApprovedComments(), $post);
		?>
	</article>
<?php
	endforeach;
}
?>

blog_Yii_2/blog/protected/modules/blog/views/post/_commentview.php
<article style="word-wrap: break-word;border:1px dotted black;" class="comment" id="c<?php echo $data->id; ?>">
	<div style="display:table;width:100%">
		<div style="display:table-cell;width:6%;vertical-align: top;">
			<?php
				echo CHtml::image(Yii::app()->baseUrl . '/' . User::IMAGE_DIRECTORY . (is_null($data->user_id) ? User::DEFAULT_IMAGE : $data->user->getImageFile()), '', array('class' => 'avatar'));
			?>				
		</div>
		<div style="display:table-cell;padding-left:10px">
			<header style="padding-bottom:5px;border-bottom: 1px solid silver;">
				<b><?php echo $data->authorLink; ?>&nbsp;&nbsp;&nbsp;
				<?php echo date('j ',$data->create_time) . Message::getTranslation(114 + date('n',$data->create_time)) . date(', Y h:i a',$data->create_time); ?>&nbsp;&nbsp;&nbsp;</b>
				<?php echo CHtml::link(Message::getTranslation(100), '#comment-form', array('class' => 'replycomment', 'rel' => 'nofollow')); ?>&nbsp;&nbsp;&nbsp;
				<?php echo CHtml::link(Message::getTranslation(197), $data->getUrl($post), array('title'=>Message::getTranslation(196), 'rel' => 'nofollow')); ?>
			</header>
			<div style="padding-top: 10px;padding-bottom: 10px;">
					<?php echo nl2br($data->content); ?>
			</div>
		</div>
	</div>
	<?php 
		printComments($data->getApprovedComments(), $post);
	?>
</article>

blog_Yii_2/blog/protected/modules/blog/views/post/_searchResult.php
<div style="margin:20px 0px;">
<?php
echo CHtml::link($data->title, $data->url);
?>
</div>

blog_Yii_2/blog/protected/modules/blog/views/post/_view.php
<div class="post">
	<div class="title">
		<?php echo CHtml::link(CHtml::encode($data->title), $data -> url); ?>
	</div>
	<div class="author">
		<?php
		if(Parameter::getValue(22)){
			echo Message::getTranslation(7) . ' ' . CHtml::link($data->user->username, $data->user->url, array('target' => '_blank', 'rel' => strpos($data->user->url, 'google') > 0 ? 'author' : null));
		}
		if(Parameter::getValue(23)){  
			echo ' '. date('j ',$data->create_time) . Message::getTranslation(114 + date('n',$data->create_time)) . date(', Y',$data->create_time);
		}
		?>	
	</div>
	<div class="content">
		<?php
			echo $data->getIntroductoryText();
		?>
	</div>
	<div class="nav">
		<?php if(Parameter::getValue(21)){ ?>
			<b><?= Message::getTranslation(4) ?>:</b>
			<?php echo implode(', ', $data->tagLinks); ?>
			<br/>
		<?php } ?>
		<?php 
			if(Parameter::getValue(25)):
				echo ' | ' . CHtml::link(Message::getTranslation(197), $data -> url, array('rel' => 'nofollow'));
			endif;
		?>
		<?php 
			if(Parameter::getValue(20)):
				echo ' | ' . CHtml::link(Message::getTranslation(17) . " ({$data->commentCount})", $data -> url . '#comments', array('rel' => 'nofollow'));
			endif; 
		?>
		<?php
			if(Parameter::getValue(24)):
				echo ' | ' . Message::getTranslation(14) . ' ' . date('j ',$data->update_time) . Message::getTranslation(114 + date('n',$data->update_time)) . date(', Y',$data->update_time);
			endif;
		?>
	</div>
</div>

blog_Yii_2/blog/protected/modules/blog/views/post/create.php
<?php
$this->pageTitle = Message::getTranslation(58);
$this->breadcrumbs=array(
	Message::getTranslation(58),
);
?>
<h1><?= Message::getTranslation(58) ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'language' => isset($language) ? $language : '')); ?>

blog_Yii_2/blog/protected/modules/blog/views/post/index.php
<?php
// главная
$this -> pageTitle = Yii::t('messages', 'L2');
$this->canonical = Yii::app()->createAbsoluteUrl('/blog/post/index', array('lang' => Yii::app()->getLanguage()));
?>
<?php if(Yii::app()->user->hasFlash('success')): ?>
<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('success'); ?>
</div>
<?php elseif(Yii::app()->user->hasFlash('error')): ?>
<div class="flash-error">
	<?php echo Yii::app()->user->getFlash('error'); ?>
</div>
<?php endif; ?>

<?php if(!empty($_GET['tag'])): ?>
<h1><?= Message::getTranslation(16) ?> <i>"<?php echo CHtml::encode(str_replace('-', ' ', $_GET['tag'])); ?>"</i></h1>
<?php endif; ?>
<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
	'template'=>"{pager}\n{items}\n{pager}",
	'pager' => array('cssFile' => Yii::app()->baseUrl . '/css/gridview.css'),
)); ?>

blog_Yii_2/blog/protected/modules/blog/views/post/searchResults.php
<h1>
<?php echo $results->totalItemCount . ' ' . Message::getTranslation(190); ?>
</h1> 
<?php
	$this->pageTitle = $results->totalItemCount . ' ' . Message::getTranslation(190);
	
	Yii::app()->clientScript->registerCss('stylesearch', '
		.items{
			text-align:center;
		}
		
		.list-view .pager
		{
			margin: 5px 0 0 0;
			text-align: center;
		}	
	');

	$this->widget('zii.widgets.CListView', array(
		'dataProvider'=>$results,
		'itemView'=>'_searchResult',
		'template'=>"{pager}\n{items}\n{pager}",
	));

blog_Yii_2/blog/protected/modules/blog/views/post/update.php
<?php
$this->pageTitle = Message::getTranslation(51);
$this->breadcrumbs=array(
	$model->title=>$model->url,
	Message::getTranslation(51),
);
?>

<h1><?= Message::getTranslation(51) ?> <i><?php echo CHtml::encode($model->title); ?></i></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>