blog_Yii_2/blog/protected/modules/blog/controllers/UserController.php
<?php

class UserController extends BlogController
{
	public $layout = '//layouts/blog';
	/**
	 * var CActiveRecord в настоящее время загружены экземпляр модели данных.
	 */
	private $_model;
	/**
	 * return массив фильтров действий
	 */
	public function filters()
	{
		$filters = array(
			'accessControl', // Выполнить контроль доступа для CRUD операций
		);
		
		return array_merge($filters, parent::filters());
	}

	/**
	 * Объявляет действия на основе классов.
	 */
	public function actions()
	{
		return array(
            // CAPTCHA на действие оказывает на изображение CAPTCHA отображается на странице контактов
			'captcha'=>array(
                'class'=>'CaptchaExtendedAction',
                // if needed, modify settings
                'testLimit' => 1,
			),
		);
	}

	/**
    Указывает правила контроля доступа.
     * Этот метод используется фильтром '' AccessControl.
     * Правила контроляreturn доступа к массиву
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('activatePassword', 'passwordRecovery', 'unsubscribe', 'register', 'confirm', 'captcha', 'categoriesByLanguage'),
				'users'=>array('*'),
			),
			array('allow',
				'actions' => array('view'),
				'users'=>array('@'),
			),
			array('allow',
				'roles'=>array('admin'),
			),
			array('allow',
				'actions' => array('update'), 
				'roles'=> array('reader','author','editor','publisher'),
			),
			array('deny',
				'users'=>array('*'),
			),
		);
	}

	/**
     * Отображение конкретной модели.
	 */
	public function actionView()
	{
		$model = $this->loadModel();
		$user = User::model()->findByPk(Yii::app()->user->id);
		$contact=new ContactForm;
		
		if(isset($_POST['ContactForm']))
		{
			$contact->attributes=$_POST['ContactForm'];
			if($contact->validate())
			{
				$model->sendEmail(Parameter::getValue(28) . ': ' . $user->username, $user->email, $contact->subject, $contact->body);
				Yii::app()->user->setFlash('contact',Message::getTranslation(187) . ' ' . $model->username);
				$this->refresh();
			}
		}
		
		$this->render('view', array('model' => $model, 'contact' => $contact));
	}

	
	/**
    Создает новую модель.
	 */
	public function actionCreate()
	{
		$model=new User('insert');
		$model->status = User::STATUS_UNCONFIRMED;
		$model->role = User::ROLE_READER;
		$model->subscribe = Parameter::getValue(30) ? true : false;
		
		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->subscribed_categories == null)
				$model->subscribed_categories = array();
			if($model->save())
			{
				Yii::app()->user->setFlash('success',Message::getTranslation(85));
				$this->redirect(array('admin', 'lang' => $_POST['lang']));
			}
		}

        $model->password = null;
		$model->repeatPassword = null;
		
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
    Создает новую модель.
	 */
	public function actionRegister()
	{
		$model=new User('register');
		$model->status = User::STATUS_UNCONFIRMED;
		$model->role = User::ROLE_READER;
		$model->subscribe = Parameter::getValue(30) ? true : false;
		
		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->subscribed_categories == null)
				$model->subscribed_categories = array();
			
			if($model->save())
			{
				Yii::app()->user->setFlash('success',Message::getTranslation(105));
				$this->redirect(array('/blog/post/index', 'lang' => Yii::app()->getLanguage()));
			}
		}

	
        $model->password = null;
		$model->repeatPassword = null;
		
		$this->render('register',array(
			'model'=>$model,
		));
	}
	
	public function actionConfirm()
	{
		if(isset($_GET['token']))
		{
			$user = User::model()->find(array('condition' => 'token = :token', 'params' => array(':token' => $_GET['token'])));
			if($user != null)
			{
				$user->scenario = 'confirm';
				$user->status = User::STATUS_ACTIVE;
				$user->save();
			}
			else {
				throw new CHttpException(404, Message::getTranslation(110));
			}
		}
		else
			throw new CHttpException(404, Message::getTranslation(110));
		
		Yii::app()->user->setFlash('success',Message::getTranslation(111));
		$this->redirect(array('/blog/post/index', 'lang' => isset($_GET['lang']) ? $_GET['lang'] : Parameter::getValue(29)));
	}
	
	public function actionUnsubscribe()
	{
		if(isset($_GET['token']))
		{
			$user = User::model()->find(array('condition' => 'token = :token', 'params' => array(':token' => $_GET['token'])));
			if($user != null)
			{
				$user->scenario = 'unsubscribe';
				$user->subscribe = 0;
				$user->save();
			}
			else {
				throw new CHttpException(404, Message::getTranslation(110));
			}
		}
		else
			throw new CHttpException(404, Message::getTranslation(110));
		
		Yii::app()->user->setFlash('success',Message::getTranslation(141));
		$this->redirect(array('/blog/post/index', 'lang' => isset($_GET['lang']) ? $_GET['lang'] : Parameter::getValue(29)));
	}
	
	/**
	 * Обновления конкретной модели.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();
		// Администраторы не могут обновлять другие админы
		if($model->authAssignment->itemname === 'admin' && Yii::app()->user->id !== $model->id)
			throw new CHttpException(404, Message::getTranslation(94));
		// Читатели, авторы, редакторы и издатель может обновлять только свои собственные профили
		if(Yii::app()->user->checkAccess('reader') || Yii::app()->user->checkAccess('author') || 
			Yii::app()->user->checkAccess('editor') || Yii::app()->user->checkAccess('publisher'))
			if(Yii::app()->user->id !== $model->id)
				throw new CHttpException(404, Message::getTranslation(94));
						
		$model->scenario='update';
		
		if(Yii::app()->user->checkAccess('admin'))
		{
			if($model->status == User::STATUS_BANNED)
			{
				if(!is_null($model->ban_expires))
				{
					$model->ban_expires = ($model->ban_expires * 1000) . '';
					$model->ban_forever = false;
				}
				else
					$model->ban_forever = true;
			}
		}
				
		if(isset($_POST['User']))
		{
			$model->attributes = $_POST['User'];
			$model->username = trim(strtolower($model->username));
			if($model->subscribed_categories == null)
				$model->subscribed_categories = array();
				
			if($model->save())
			{
				Yii::app()->user->setFlash('success',Message::getTranslation(86));
				if(Yii::app()->user->checkAccess('admin'))
					$this->redirect(array('admin', 'lang' => $_POST['lang']));
				else
					$this->redirect(array('/blog/post/index', 'lang' => $_POST['lang']));
			}
		}

        $model->password = null;
		$model->repeatPassword = null;
		
		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Удаляет конкретную модель.
	 */
	public function actionDelete()
	{
		// we only allow deletion via POST request
		$model = $this->loadModel();
		$model->delete();
		
		switch($model->onDeleteError)
		{
			case 0:
				Yii::app()->user->setFlash('success',Message::getTranslation(87));
				break;
			case 1:
				Yii::app()->user->setFlash('error',Message::getTranslation(88));
				break;
			case 2:
				Yii::app()->user->setFlash('error', Message::getTranslation(143));
				break;
		}

        // Если AJAX запрос (вызвано удаление с помощью зрения администратора сетки), мы не должны перенаправить браузер
		if(!isset($_GET['ajax']))
		{
			$this->redirect(array('admin', 'lang' => $_GET['lang']));
		}
	}
	
	
	/**
	 * Управляет всеми моделями.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];
		$this->render('admin',array(
			'model'=>$model,
		));
	}


	/**
	 * Возвращает модель данных на основе первичного ключа, указанному в переменной GET.
     * Если модель данных не найден, HTTP будет возбуждено исключение.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['user']))
			{
				$this->_model=User::model()->findByPk($_GET['user']);
			}
			if($this->_model===null)
				throw new CHttpException(404,Message::getTranslation(94));
		}
		return $this->_model;
	}
	
	public function actionCategoriesByLanguage()
	{
		$categories = Category::model()->findAll(array('condition' => 'language =\'' . $_POST['languages']. '\' AND category_id IS NULL','order' => 'LOWER(name) ASC'));
		$this->getListData($categories, 0);	
	}
	
	private function getListData($categories, $level)
	{			
		foreach($categories as $category)
		{
			$lines = '';
			for($i = 0; $i < $level; $i++)
				$lines .= '--';
			echo "<option value=\"{$category->id}\">{$lines}{$category->name}</option>";
			$this->getListData($category->categories, $level + 1);
		}		
	}
	
	/**
	 * Восстановление пароля.
	 */
	public function actionPasswordRecovery()
	{
		$model=new PasswordRecovery;
		
		if(isset($_POST['PasswordRecovery']))
		{
			$model->attributes=$_POST['PasswordRecovery'];
			if($model->validate())
			{
				$user = User::model()->find('email=?', array($model->email));
				if(!is_null($user))
				{
					$password = User::generatePassword(10);
					$user->scenario = "passwordrecovery";
					$user->new_password = CPasswordHelper::hashPassword($password);
					if($user->save())
					{
						$user->sendNewPassword($password);
						Yii::app()->user->setFlash('success',Message::getTranslation(184));
						$this->refresh();
					}
					else {
						throw new CHttpException(404, Message::getTranslation(110));
					}
				}
				$model->addError('email', Message::getTranslation(183));
			}
		}
		
		$this->render('password_recovery', array('model' => $model));
	}
	
	public function actionActivatePassword()
	{
		if(isset($_GET['token']))
		{
			$user = User::model()->find(array('condition' => 'token = :token', 'params' => array(':token' => $_GET['token'])));
			if($user != null && $user->new_password != null)
			{
				$user->scenario = 'activatepassword';
				$user->password = $user->repeatPassword = $user->new_password;
				$user->new_password = null;
				$user->save();
			}
			else {

blog_Yii_2/blog/protected/modules/blog/views/user/admin.php
<?php
$this->pageTitle = Message::getTranslation(67);
$this->breadcrumbs=array(
	Message::getTranslation(67),
);
$style ='	@media 
	all and (max-width: 950px),
	(min-device-width: 768px) and (max-device-width: 1024px)  {
		td:nth-of-type(1):before { content: "' . Message::getTranslation(43) . '"; }
		td:nth-of-type(2):before { content: "' . Message::getTranslation(11) . '"; }
		td:nth-of-type(3):before { content: "' . Message::getTranslation(12) . '"; }
		td:nth-of-type(4):before { content: "' . Message::getTranslation(137) . '"; }
		td:nth-of-type(5):before { content: "' . '#' . substr(Message::getTranslation(17),0,3) . '"; }
		td:nth-of-type(6):before { content: "' . Message::getTranslation(42) . '"; }
		td:nth-of-type(7):before { content: "' . Message::getTranslation(31) . '"; }
		td:nth-of-type(8):before { content: "' . Message::getTranslation(138) . '"; }
		td:nth-of-type(9):before { content: "' . Message::getTranslation(30) . '"; }
		td:nth-of-type(10):before { content: "' . Message::getTranslation(139) . '"; }
	}';
Yii::app()->getClientScript()->registerCss('style', $style);
?>
<?php if(Yii::app()->user->hasFlash('success')): ?>
<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('success'); ?>
</div>
<?php elseif(Yii::app()->user->hasFlash('error')): ?>
<div class="flash-error">
	<?php echo Yii::app()->user->getFlash('error'); ?>
</div>
<?php endif; ?>

<h1><?= Message::getTranslation(67) ?></h1>
<div style="text-align:center;margin-bottom:20px;">
<?php echo CHtml::link(Message::getTranslation(50),array('user/create', 'lang' => Yii::app()->getLanguage()), array('class' => 'btncreate')); ?>
</div>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'pager' => array('cssFile' => Yii::app()->baseUrl . '/css/gridview.css'),
	'cssFile' => Yii::app()->baseUrl . '/css/gridview.css',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'htmlOptions' => array('class' => 'grid-view rounded'),
	'ajaxUpdate'=>false,
	'columns'=>array(
		array(
			'name'=>'username',
			'type'=>'raw',
			'value'=>'CHtml::link($data->username, array("/blog/user/view", "user" => $data->id, "lang" => Yii::app()->getLanguage()))'
		),
		array(
			'name'=>'email',
			'type'=>'raw',
			'value'=>'$data->email',
		),
		array(
			'name'=>'url',
			'type'=>'raw',
			'value'=>'CHtml::link($data->url, $data->url, array("target" => "_blank"))',
		),
		array(
			'name'=>'role',
			'value'=>'$data->role',
			'filter'=>AuthItem::getRolesOptions()
		),
		array(
			'name'=>'commentCount',
			'type'=>'raw',
			'value'=>'$data->commentCount',
    		'filter'=>false,
		),
		array(
			'name'=>'image',
			'type'=>'raw',
			'value'=>'CHtml::image(Yii::app()->baseUrl . "/" . User::IMAGE_DIRECTORY . $data->getImageFile(), "", array("class" => "avatar"))',
			'filter'=>false,
		),
		array(
			'name'=>'create_time',
			'type'=>'datetime',
			'filter'=>false,
		),
		array(
			'name'=>'last_visit',
			'type'=>'datetime',
			'filter'=>false,
		),
		array(
			'name'=>'status',
			'value'=>'Lookup::item("UserStatus",$data->status)',
			'filter'=>Lookup::items('UserStatus'),
		),
        array(
        	'htmlOptions'=>array('style'=>'width:70px'),
            'header' => Message::getTranslation(49),
            'class' => 'CButtonColumn',
            'template' => '{update}&nbsp;{delete}',
            'viewButtonImageUrl' => Yii::app()->baseUrl . '/images/gridview/' . 'gr-view.png',
            'updateButtonImageUrl' => Yii::app()->baseUrl . '/images/gridview/' . 'gr-update.png',
            'deleteButtonImageUrl' => Yii::app()->baseUrl . '/images/gridview/' . 'gr-delete.png',
	        'buttons'=>array
			(
		       /*'view' => array
		        (
		        	'url'=>'Yii::app()->createUrl("/blog/user/view", array("user"=>$data->id, "lang" => Yii::app()->getLanguage()))'
		        ),*/
		       'update' => array
		        (
		        	'url'=>'Yii::app()->createUrl("/blog/user/update", array("user"=>$data->id, "lang" => Yii::app()->getLanguage()))'
		        ),
		       'delete' => array
		        (
		        	'url'=>'Yii::app()->createUrl("/blog/user/delete", array("user"=>$data->id, "lang" => Yii::app()->getLanguage()))'
		        ),
			),
         ),
	),
)); ?>

blog_Yii_2/blog/protected/modules/blog/views/user/create.php
<?php
$this->pageTitle = Message::getTranslation(61);
$this->breadcrumbs=array(
	Message::getTranslation(61),
);
?>
<h1><?= Message::getTranslation(61) ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

blog_Yii_2/blog/protected/modules/blog/views/user/password_recovery.php
<?php
	$this->pageTitle = Message::getTranslation(173);
	Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl . '/css/form.css');
?>
<center>
<h1><?= Message::getTranslation(173) ?></h1>
<?php if(Yii::app()->user->hasFlash('success')): ?>
<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('success'); ?>
</div>
<?php elseif(Yii::app()->user->hasFlash('error')): ?>
<div class="flash-error">
	<?php echo Yii::app()->user->getFlash('error'); ?>
</div>
<?php endif; ?>
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
		'htmlOptions' => array('enctype' => 'multipart/form-data')
	)); ?>
	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('autocomplete' => 'off')); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>
	<?php if(CCaptcha::checkRequirements()): ?>
		<div class="row">
			<?php echo $form->labelEx($model,'verifyCode'); ?>
				<?php $this->widget('CCaptcha'); ?>
				<br/>
				<?php echo $form->textField($model,'verifyCode'); ?>
				<div style="color:black;" class="hint">
					<?= Message::getTranslation(148) ?>
				</div>
			<?php echo $form->error($model,'verifyCode'); ?>
		</div>
	<?php endif; ?>	
	<div class="row buttons">
		<?php 
			echo CHtml::submitButton("Submit", array('class' => 'bigbutton'));
		?>
	</div>

<?php $this->endWidget(); ?>
</div>
</center>

blog_Yii_2/blog/protected/modules/blog/views/user/register.php
<?php
$this->pageTitle = Message::getTranslation(104);
$this->breadcrumbs=array(
	Message::getTranslation(104),
);
?>

<h1><?= Message::getTranslation(104) ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

blog_Yii_2/blog/protected/modules/blog/views/user/update.php
<?php
$this->pageTitle = Message::getTranslation(55);
$this->breadcrumbs=array(
	Message::getTranslation(55),
);
?>

<h1><?= Message::getTranslation(55) ?> <i><?php echo CHtml::encode($model->username); ?></i></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

blog_Yii_2/blog/protected/modules/blog/views/user/view.php
<?php
	$this->pageTitle = $model->username;
	Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl . '/css/form.css');
	$userviewstyle = '
		td{
			border:1px solid black;
			word-break: break-all;
			padding-left: 10px;
			padding-right: 10px;
		}
		td:nth-child(1){
			background: gray;
			font-weight: bold;
			color: white;
			width:130px;
		}
		table
		{
			margin-bottom: 20px;
			width: 100%;
			border:1px solid black;
		}
	';
	Yii::app()->clientScript->registerCss('userview', $userviewstyle);
?>
<table>
	<tr>
		<td>
			<?= Message::getTranslation(43) ?>
		</td>
		<td>
			<?= $model->username ?>
		</td>
	</tr>
	<tr>
		<td>
			<?= Message::getTranslation(31) ?>
		</td>
		<td>
			<?php echo date('j ',$model->create_time) . Message::getTranslation(114 + date('n',$model->create_time)) . date(', Y',$model->create_time); ?>
		</td>
	</tr>
	<tr>
		<td>
			<?= Message::getTranslation(12) ?>
		</td>
		<td>
			<?= CHtml::link($model->url, $model->url, array('target' => '_blank')) ?>
		</td>
	</tr>
	<tr>
		<td>
			<?= Message::getTranslation(42) ?>
		</td>
		<td>
			<?= CHtml::image(Yii::app()->baseUrl . '/' . User::IMAGE_DIRECTORY . $model->getImageFile(), '', array('style' => 'max-width:100%;border:1px solid black;')); ?>
		</td>
	</tr>
	<tr>
		<td>
			#<?= Message::getTranslation(17) ?>
		</td>
		<td>
			<?= $model->commentCount ?>
		</td>
	</tr>
	<tr>
		<td>
			<?= Message::getTranslation(153) ?>
		</td>
		<td>
			<?php $this->beginWidget('CMarkdown', array('purifyOutput' => true));
				echo $model->additional_info;
			$this->endWidget();?>
		</td>
	</tr>
</table>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

	<div style="text-align: center;background:url(<?= Yii::app()->baseUrl . '/images/bgmail.jpg' ?>);background-size:100% 100%;border:1px solid black;padding-top:25px;" class="form">
	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>'contact-form',
		'htmlOptions' => array('style' => 'text-align: center;')
	)); ?>
		<span style="font-size:30px"><?= Message::getTranslation(181) ?></span>
		<p style="margin-top:30px;"><?= Message::getTranslation(8) ?></p>
	
		<?php echo $form->errorSummary($contact); ?>
	
		<div class="row">
			<?php echo $form->labelEx($contact,'subject', array('class' => 'shadowtext')); ?>
			<?php echo $form->textField($contact,'subject',array('size'=>40,'maxlength'=>128, 'class' => 'inputtext')); ?>
			<?php echo $form->error($contact,'subject'); ?>
		</div>
	
		<div class="row">
			<?php echo $form->labelEx($contact,'body', array('class' => 'shadowtext')); ?>
			<?php echo $form->textArea($contact,'body',array('rows'=>6, 'cols'=>50, 'class' => 'inputtext')); ?>
			<?php echo $form->error($contact,'body'); ?>
		</div>
	
		<div class="row buttons">
			<?php echo CHtml::submitButton(Message::getTranslation(186), array('class' => 'bigbutton')); ?>
		</div>
	
	<?php $this->endWidget(); ?>
	
	</div><!-- form -->
<?php endif; ?>